### ISSUE TITLE
No functionality for adding a profile picture

### ISSUE THREAD

**Issue by rgroves** [learnwithjason/learnwithjason.dev-v2#12]
This seems like missing functionality when creating/editing an account profile.

@jlengstorf if you want to leave a some directional notes about how you'd like photo uploads handled or if you want to use an external system (like Gravatar) for profile images, I'm up for trying to work on a PR for this.

**Comment by jlengstorf** [comment]
oh, this is a good point — it's done through Clerk, and I don't think I have a link to the Clerk profile management page. probably good to add near the profile photo, I think. I should be able to add that soon
